### ISSUE TITLE
add a navbar with cool animations

### ISSUE THREAD

**Issue by Sayak-Bhunia** [Sayak-Bhunia/mystory#1]

**Comment by psidh** [comment]
I want to work on creating navbar, @Sayak-Bhunia can you assign me this issue

**Comment by Sayak-Bhunia** [comment]
> I want to work on creating navbar, @Sayak-Bhunia can you assign me this issue

assigned.

**Comment by Sayak-Bhunia** [comment]
> I want to work on creating navbar, @Sayak-Bhunia can you assign me this issue

Please show me the design before implementing it and do make it responsive.

**Comment by psidh** [comment]
This is the design I have in mind - with `LIVE implementation`

https://github.com/Sayak-Bhunia/mystory/assets/116720762/483fdbef-da99-4d8f-bbfe-43433eaaca8c

**Comment by Sayak-Bhunia** [comment]
> 
> This is the design I have in mind - with `LIVE implementation`
> 
> https://github.com/Sayak-Bhunia/mystory/assets/116720762/483fdbef-da99-4d8f-bbfe-43433eaaca8c
> 
> 

The design for large screen is good but the design for the small screen can be improved so try to take inspiration from any ui components library or ui bolhs like Oliver larose or rauno.me or from any vercel dx dev

**Comment by psidh** [comment]
Oh Okay, working on it...

**Comment by Sayak-Bhunia** [comment]
instead of using blue try to keep the color combo to #191919 and #F1F5F9.

**Comment by Sayak-Bhunia** [comment]
do star the repo.

**Comment by psidh** [comment]
1. Added padding to the large links
2. made the `menu` to `cross` while closing
3. made `uniform width` and animation to open link
4. `color` scheme changed


https://github.com/Sayak-Bhunia/mystory/assets/116720762/d3fbf4d6-4f48-4a5f-9beb-6691eaf92a57

**Comment by Sayak-Bhunia** [comment]
Thats great 👍🏻
Now raise the PR.

**Comment by Sayak-Bhunia** [comment]
merged!
