### ISSUE TITLE
[BUG]: Confession is not Working

### ISSUE THREAD

**Issue by Sayak-Bhunia** [Sayak-Bhunia/mystory#102]
Fix it the confession should be with a username

**Comment by mohdjami** [comment]
Assign this issue to me.

**Comment by Sayak-Bhunia** [comment]
> Assign this issue to me.

assigned.

**Comment by Sayak-Bhunia** [comment]
any updates ?

**Comment by mohdjami** [comment]
@Sayak-Bhunia, I need to see server logs. Why is there problem in authentication first. Furthermore, confessions are working perfectly fine locally. When I created my own deployment everything is fine check it out https://mystory-three.vercel.app/ try sign in with GitHub and then create a confession.

**Comment by Sayak-Bhunia** [comment]
> @Sayak-Bhunia, I need to see server logs. Why is there problem in authentication first. Furthermore, confessions are working perfectly fine locally. When I created my own deployment everything is fine check it out https://mystory-three.vercel.app/ try sign in with GitHub and then create a confession.

Ya auth works on this properly may be we should make this the main branch?

**Comment by mohdjami** [comment]
@Sayak-Bhunia , lets give it a try.

**Comment by mohdjami** [comment]
@Sayak-Bhunia ,Let's fix authentication today. Let me know when you are free today. We can have a meet.

**Comment by Sayak-Bhunia** [comment]
> @Sayak-Bhunia ,Let's fix authentication today. Let me know when you are free today. We can have a meet.

At 5pm ?

**Comment by mohdjami** [comment]
@Sayak-Bhunia we can close this issue and the authentication one right?

**Comment by Sayak-Bhunia** [comment]
ya.
