### ISSUE TITLE
[BUG]: Authentication is showing server error

### ISSUE THREAD

**Issue by Sayak-Bhunia** [Sayak-Bhunia/mystory#103]
Fix it ASAP.

**Comment by mohdjami** [comment]
@Sayak-Bhunia Did you check if all the env variables are set?

**Comment by mohdjami** [comment]
Hey @Sayak-Bhunia , are you available for a short meet at discord? Let's connect on [linkedIn](https://LinkedIn.com/in/mohdjami) and discuss more about this issue.

**Comment by Sayak-Bhunia** [comment]
> Hey @Sayak-Bhunia , are you available for a short meet at discord? Let's connect on [linkedIn](https://LinkedIn.com/in/mohdjami) and discuss more about this issue.

Okay discord username - sayak2903 #3065

**Comment by mohdjami** [comment]
@Sayak-Bhunia , Github Sign In is not working because you have to paste this url https://mystorybuild.vercel.app/api/auth on the github mystory Oauth app instead of https://github.com/Sayak-Bhunia/mystory/ this url. Authentication issue will be fixed After that.

**Comment by Sayak-Bhunia** [comment]
on the homepage url or Authorization callback URL ?

**Comment by Sayak-Bhunia** [comment]
ok its working fine now.
