### ISSUE TITLE
[Feature] : Add About Page

### ISSUE THREAD

**Issue by ayushnandi** [Sayak-Bhunia/mystory#107]
### Issue
I want to create an "About" page to provide visitors with information about the site, mission, goals and other relevant details.

### Proposed design: 
![image](https://github.com/Sayak-Bhunia/mystory/assets/110190468/962286d6-893d-4294-85ec-c17e1b016899)

### Expected Outcome
The "About" page should provide a comprehensive overview of the site, its mission, and the team, enhancing the visitor's understanding and trust. also adding skeleton page into is this can make it look more interactive

kindly assign me this issue under GSSoC '24

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by TenzDelek** [comment]
@ayushnandi  are you still on it or else should I take over the issue?
cc @Sayak-Bhunia

**Comment by ayushnandi** [comment]
![image](https://github.com/Sayak-Bhunia/mystory/assets/110190468/b7d085c9-0cc0-485a-809e-0d1e43a39a60)

here i have currently created a static design , and if you can provide me content i can put into it , or  should i push it for now ?

**Comment by TenzDelek** [comment]
> ![image](https://private-user-images.githubusercontent.com/110190468/333848221-b7d085c9-0cc0-485a-809e-0d1e43a39a60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDA4NzQsIm5iZiI6MTcxNjcwMDU3NCwicGF0aCI6Ii8xMTAxOTA0NjgvMzMzODQ4MjIxLWI3ZDA4NWM5LTBjYzAtNDg1YS04MDllLTBkMWU0M2EzOWE2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQwNTE2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzhiZmEwNmQ1YjQwNjFmYzc3NDdiYjcyNjRmOWYxMDIzY2QzMDdjYjNlMzg0YzRkNzMxMGYzMjBmNGNlNjQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.keonOOzQ0dA65qJ-tQuuBrdXmW1ZMKld_EKXx4rcVuY)
> 
> here i have currently created a static design , and if you can provide me content i can put into it , or should i push it for now ?

input:
try to put description from the readme file, also it better to put image of @Sayak-Bhunia  instead of a static one.  
also make sure it is both compatible for both dark mode and light mode.

**Comment by ayushnandi** [comment]
![image](https://github.com/Sayak-Bhunia/mystory/assets/110190468/7ff4c8ef-29be-4ea7-81aa-638e2164990d)

this is the updated description, and also let me know if any corrections have to be made

**Comment by TenzDelek** [comment]
> ![image](https://private-user-images.githubusercontent.com/110190468/333881428-7ff4c8ef-29be-4ea7-81aa-638e2164990d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Mjk1OTIsIm5iZiI6MTcxNjcyOTI5MiwicGF0aCI6Ii8xMTAxOTA0NjgvMzMzODgxNDI4LTdmZjRjOGVmLTI5YmUtNGVhNy04MWFhLTYzOGUyMTY0OTkwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxMzE0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTc2MWI1OGEwMjg1M2NkZDc4NjJiODNmMTkwNzRlYjc1MGFjNWViNTZhYjY0NDU5MWMzNzA1MGQzYjJiYTdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D7hCDMHvWwIYIhs4aHYa9hQ895j7U92KFWrqoY2xKSk)
> 
> this is the updated description, and also let me know if any corrections have to be made

cc @Sayak-Bhunia

**Comment by Sayak-Bhunia** [comment]
> ![image](https://private-user-images.githubusercontent.com/110190468/333881428-7ff4c8ef-29be-4ea7-81aa-638e2164990d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzAxMjMsIm5iZiI6MTcxNjcyOTgyMywicGF0aCI6Ii8xMTAxOTA0NjgvMzMzODgxNDI4LTdmZjRjOGVmLTI5YmUtNGVhNy04MWFhLTYzOGUyMTY0OTkwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxMzIzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjUxMTI1NjU5MWFhYWMxNWE0MDQzMTc0MGViOWYxNjI2OGMxODI1MTk1MjI4NTM1MzE3ZmJhY2E3NmM2MjgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XuoYNHYW6dkev-kyt4J_4C83CD7yc2POgOTrrV1kSXU)
> 
> this is the updated description, and also let me know if any corrections have to be made

make this compatitable for dark and light mode both. like @TenzDelek said.

**Comment by Vaibhavsg17** [comment]
@ayushnandi are you still working on this? 
if not should I take up the issue @Sayak-Bhunia ?

**Comment by ayushnandi** [comment]
Hi @Sayak-Bhunia ,

I noticed that the project currently does not have a common dark mode feature. Adding dark mode specifically to the about page would require modifications to several files. To implement this feature efficiently and cohesively, I propose creating a new issue for adding a comprehensive dark mode to the entire project.

If you agree, I can create the issue and start working on it. Please let me know your thoughts, and feel free to assign the task to me if you find it suitable.

Additionally, I would like to inform you that the task previously assigned to me has been completed.
![image](https://github.com/Sayak-Bhunia/mystory/assets/110190468/7ff4c8ef-29be-4ea7-81aa-638e2164990d)

**Comment by Kritika30032002** [comment]
@Sayak-Bhunia  check this

**Comment by Kritika30032002** [comment]
@ayushnandi  Hey! Can you work more on improving UI part

**Comment by ayushnandi** [comment]
Hey @Kritika30032002 !

I will be more than happy to contribute more to this project.
Let me know if you need any more assistance!
