### ISSUE TITLE
[Feature] Settings Page

### ISSUE THREAD

**Issue by mohdjami** [Sayak-Bhunia/mystory#109]
I want to create a settings page for this application, where users can edit their username and other things. Assign this issue to me under GSSoC'24

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by shresthaPandit** [comment]
Hey @Sayak-bhuniya, @Mohdjami, I believe I can work on this issue and raise a PR today or tomorrow. 
Approach: I will create a route in the backend to update the user name. And for frontend I will create a settings page where I will create a form to update the username.

Please assign me this issue under GSSoC'24 @sayak-bhuniya and @mohdjami. It will be my first contribution in GSSoC'24

**Comment by shresthaPandit** [comment]
Hey @Sayak-Bhunia , @mohdjami , I believe I can work on this issue and raise a PR today or tomorrow. 
Approach: I will create a route in the backend to update the user name. And for frontend I will create a settings page where I will create a form to update the username.

Please assign me this issue under GSSoC'24 @sayak-bhuniya and @mohdjami. It will be my first contribution in GSSoC'24

**Comment by Sayak-Bhunia** [comment]
> Hey @Sayak-Bhunia , @mohdjami , I believe I can work on this issue and raise a PR today or tomorrow. 
> Approach: I will create a route in the backend to update the user name. And for frontend I will create a settings page where I will create a form to update the username.
> 
> Please assign me this issue under GSSoC'24 @sayak-bhuniya and @mohdjami. It will be my first contribution in GSSoC'24

Its already assigned to @mohdjami.

**Comment by mohdjami** [comment]
Okay @shresthaPandit, @Sayak-Bhunia assign him this issue. I am already working on 3 issues.

**Comment by Sayak-Bhunia** [comment]
> Okay @shresthaPandit, @Sayak-Bhunia assign him this issue. I am already working on 3 issues.

Okay @mohdjami the issue is assigned to u @shresthaPandit.

**Comment by Sayak-Bhunia** [comment]
> > Okay @shresthaPandit, @Sayak-Bhunia assign him this issue. I am already working on 3 issues.
> 
> Okay @mohdjami the issue is assigned to u @shresthaPandit.

@shresthaPandit best of luck 🤞 for ur valuable contribution🍀and do ⭐ the repo.

**Comment by shresthaPandit** [comment]
Thanks @Sayak-Bhunia  I will start working today

**Comment by shresthaPandit** [comment]
@Sayak-Bhunia  Do you need anything else in the settings page other than username update

**Comment by Sayak-Bhunia** [comment]
> @Sayak-Bhunia  Do you need anything else in the settings page other than username update

No.

**Comment by shresthaPandit** [comment]
hey @Sayak-Bhunia I have sucessfully created a PR please review and merge it .
