### ISSUE TITLE
Enigma themed landing page

### ISSUE THREAD

**Issue by Sushanth-Hebri** [Sayak-Bhunia/mystory#11]
### Current landing page is simple, lets make it more interactive and suspenseful , 

**1. Website name
2. Tagline
3. CTA button
4. what is this website about** 

as `anonymous ` story treasure lets make it secure and more appealing.
 Assign this task to me.

**Comment by Sayak-Bhunia** [comment]
> ### Current landing page is simple, lets make it more interactive and suspenseful ,
> **1. Website name 2. Tagline 3. CTA button 4. what is this website about**
> 
> as `anonymous ` story treasure lets make it secure and more appealing. Assign this task to me.

@psidh is already assigned with this issue if he is unable to raise a PR within 5 days then I will assign this issue to you.

**Comment by Sayak-Bhunia** [comment]
> ### Current landing page is simple, lets make it more interactive and suspenseful ,
> **1. Website name 2. Tagline 3. CTA button 4. what is this website about**
> 
> as `anonymous ` story treasure lets make it secure and more appealing. Assign this task to me.

do star the repo

**Comment by Sushanth-Hebri** [comment]
👍

**Comment by rishyym0927** [comment]
Hi @Sayak-Bhunia 

I want to work on this issue under GSSOC24. Please assign it to me.

Thanks

**Comment by Sayak-Bhunia** [comment]
@psidh is already assigned with this issue if he is unable to raise a PR within 5 days then I will assign this issue to you @rishyym0927 .
