### ISSUE TITLE
feat : Adding a password toggling facility in login/signup

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Sayak-Bhunia/mystory#116]
Adding a password toggling ability will help the user to hide and show password .
![Screenshot 2024-05-18 114021](https://github.com/Sayak-Bhunia/mystory/assets/118350936/48c39568-5d86-46c5-88a7-6b5ec107d85e)

**Comment by Sayak-Bhunia** [comment]
assigned.
do star the repo.

**Comment by Ayushmaanagarwal1211** [comment]
Sure
