### ISSUE TITLE
[BUG] Buttons in the FAQ's page are not well aligned 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Sayak-Bhunia/mystory#117]
In the faq's page the down arrow buttons are not aligned properly ,
![Screenshot 2024-05-18 114330](https://github.com/Sayak-Bhunia/mystory/assets/118350936/b31f2fd4-2c9d-4a8d-be2d-d4c910ca328d)

**Comment by Sayak-Bhunia** [comment]
assigned.
