### ISSUE TITLE
[ENHANCEMENT] Hovering effect on the faq's questions on opening .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Sayak-Bhunia/mystory#118]
I think adding a hovering animation will increase the UI/UX of the website . When user clicks on the down arrow and the respected question will be opened by giving some opening animation .
![Screenshot 2024-05-18 114502](https://github.com/Sayak-Bhunia/mystory/assets/118350936/21fa55ef-0ea5-41ce-9e5a-271db52c1543)

**Comment by Sayak-Bhunia** [comment]
assigned.
