### ISSUE TITLE
Adding a interactive Story Confessing Page 

### ISSUE THREAD

**Issue by pranjali-srvstv** [Sayak-Bhunia/mystory#12]
@Sayak-Bhunia As much as I loved this project, I would also like to make it a bit more interactive by adding a separate page for confessing personal stories, which people think that should be read by other. I'm a GSSOC'24 contributor and would kindly request you to assign this issue to me. Thank you.

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by Sayak-Bhunia** [comment]
do star the repo first.

**Comment by Sayak-Bhunia** [comment]
any updates ?
