### ISSUE TITLE
[Enhancement] in Loading.jsx page

### ISSUE THREAD

**Issue by anujsingh4545** [Sayak-Bhunia/mystory#123]
- Issue : The loading effect looks preety much blunt, we can enhance it.

- Issue Formation : Visit the Faq/ login/ signup page.

- Issue Screenshot
<img width="958" alt="image" src="https://github.com/Sayak-Bhunia/mystory/assets/76861751/d919f081-b716-4906-aacf-457a943403fc">

- Update : Already working on this.

**Comment by Kritika30032002** [comment]
@Sayak-Bhunia  add labels to it
