### ISSUE TITLE
[Bug] Hard Reloading of pages are happening.

### ISSUE THREAD

**Issue by anujsingh4545** [Sayak-Bhunia/mystory#126]
- Issue : On clicking on each tab, the page is getting hard reloading, which is compromising the overall performance.
- Issue Formation : Click on any tab, see at the website top, page gets hard reloaded.
- Issue Video

https://github.com/Sayak-Bhunia/mystory/assets/76861751/d95520f1-3db3-4039-8d4e-4aaaba3c17b1

- Update : Already working into this.

**Comment by Sayak-Bhunia** [comment]
> - Issue : On clicking on each tab, the page is getting hard reloading, which is compromising the overall performance.
> - Issue Formation : Click on any tab, see at the website top, page gets hard reloaded.
> - Issue Video
> 
> https://github.com/Sayak-Bhunia/mystory/assets/76861751/d95520f1-3db3-4039-8d4e-4aaaba3c17b1
> 
> - Update : Already working into this.

assigned.
