### ISSUE TITLE
Bug: fixing the colour alignment of everything in black and white mode 

### ISSUE THREAD

**Issue by TenzDelek** [Sayak-Bhunia/mystory#130]
the current dark mode , some text are black which makes it not visible
<img width="1119" alt="image" src="https://github.com/Sayak-Bhunia/mystory/assets/122612557/ab3b8006-8228-4615-91cf-d618f83bca3a">

**Comment by TenzDelek** [comment]
more like the invert is wrongly put
<img width="998" alt="image" src="https://github.com/Sayak-Bhunia/mystory/assets/122612557/241e0f2f-fa7b-4133-ae99-6b5201365cec">
<img width="445" alt="image" src="https://github.com/Sayak-Bhunia/mystory/assets/122612557/dab2c621-9658-470d-ab25-1e95a36072ee">

**Comment by Sayak-Bhunia** [comment]
> more like the invert is wrongly put
> <img width="998" alt="image" src="https://github.com/Sayak-Bhunia/mystory/assets/122612557/241e0f2f-fa7b-4133-ae99-6b5201365cec">
> <img width="445" alt="image" src="https://github.com/Sayak-Bhunia/mystory/assets/122612557/dab2c621-9658-470d-ab25-1e95a36072ee">
> <img width="992" alt="image" src="https://github.com/Sayak-Bhunia/mystory/assets/122612557/40611fd1-c6aa-414a-8d72-f4bcab8c73c0">
> 
> 

@sivaprasath2004 has completely messed the design.
So @Che140401 I want you to please fix the design like it was before please 🥺

**Comment by Sayak-Bhunia** [comment]
no need for this now.
