### ISSUE TITLE
Feature Toggle bar rotate

### ISSUE THREAD

**Issue by Che140401** [Sayak-Bhunia/mystory#133]
**Preveious button is not rotating**

https://github.com/Sayak-Bhunia/mystory/assets/109230049/4be3f47f-b30a-4f62-bac9-b75423023b75

**Button not rotating**

https://github.com/Sayak-Bhunia/mystory/assets/109230049/5e096b03-86cc-4024-a522-a48d90cc8bdd

**Comment by Sayak-Bhunia** [comment]
no need for this feature now.
