### ISSUE TITLE
Feature: Fotter navbar Focus

### ISSUE THREAD

**Issue by Che140401** [Sayak-Bhunia/mystory#134]
**Footer navbar focus if we want**

https://github.com/Sayak-Bhunia/mystory/assets/109230049/b9243266-cf07-4605-9c37-d4f4cf660b91

**Previous navbar dot have focus**

https://github.com/Sayak-Bhunia/mystory/assets/109230049/61db4cfa-de47-41fe-8649-8b282be990ed

**Comment by Sayak-Bhunia** [comment]
assigned.
but make a fork of the new main branch the do your changes.

**Comment by Kritika30032002** [comment]
@Che140401 updates?
