### ISSUE TITLE
Add a cards section which will contain different stories 

### ISSUE THREAD

**Issue by Sayak-Bhunia** [Sayak-Bhunia/mystory#14]

**Comment by rishyym0927** [comment]
Hi @Sayak-Bhunia 

I want to work on this issue under GSSOC24. Please assign it to me.

Thanks

**Comment by Sayak-Bhunia** [comment]
> Hi @Sayak-Bhunia 
> 
> I want to work on this issue under GSSOC24. Please assign it to me.
> 
> Thanks

assigned.

**Comment by Sayak-Bhunia** [comment]
any updates ?

**Comment by rishyym0927** [comment]
> any updates ?

working on it

**Comment by Kritika30032002** [comment]
@rishyym0927 any updates?
