### ISSUE TITLE
Designing a logo for mystory

### ISSUE THREAD

**Issue by MehtabAsHellic** [Sayak-Bhunia/mystory#142]
[https://sites.google.com/view/uibymehtab](https://github.com/Nactore-Org/Nacto-Care/issues/url)

let me know by check out my portfolio

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by MehtabAsHellic** [comment]
should I design the logo color according to the current theme of the site https://mystorybuild.vercel.app/,
or you want it as new branding identity

**Comment by MehtabAsHellic** [comment]
> should I design the logo color according to the current theme of the site https://mystorybuild.vercel.app/, or @Sayak-Bhunia 
 you want it as new branding identity

**Comment by MehtabAsHellic** [comment]
> assigned.

![Mystory Logo](https://github.com/Sayak-Bhunia/mystory/assets/101495398/b608748f-6b9f-44d0-839f-13757c8ae41d)

**Please provide you suggestion if any because we can iterate design and make more toward your requirement too.**

**Comment by Sayak-Bhunia** [comment]
> > assigned.
> 
> ![Mystory Logo](https://github.com/Sayak-Bhunia/mystory/assets/101495398/b608748f-6b9f-44d0-839f-13757c8ae41d)
> @Sayak-Bhunia 
> **Please provide you suggestion if any because we can iterate design and make more toward your requirement too.**

Hey as u can see on the website and everywhere mystory is in small letters so can you implement that and instead of using a pen to make it look like e story writing platform focus more on the anonymity like use a lock or gears or something like that represents anonymity safety of the data o users.

**Comment by MehtabAsHellic** [comment]
> > > assigned.
> > 
> > 
> > ![Mystory Logo](https://private-user-images.githubusercontent.com/101495398/333069252-b608748f-6b9f-44d0-839f-13757c8ae41d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1Mjg2NzMsIm5iZiI6MTcxNjUyODM3MywicGF0aCI6Ii8xMDE0OTUzOTgvMzMzMDY5MjUyLWI2MDg3NDhmLTZiOWYtNDRkMC04MzlmLTEzNzU3YzhhZTQxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwNTI2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTAxM2RhZjFiYzUyNjVkYTk4MjVhOWRiYTlmMmNlMGUxMzA4MWZlMDNhNzQzODFkNDg5YjRiNWVmOThlZTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wfixPzGtQiLQvokIYSnPqyz8wldXyCQxA_HitS5HiFk)
> > @Sayak-Bhunia
> > **Please provide you suggestion if any because we can iterate design and make more toward your requirement too.**
> 
> Hey as u can see on the website and everywhere mystory is in small letters so can you implement that and instead of using a pen to make it look like e story writing platform focus more on the anonymity like use a lock or gears or something like that represents anonymity safety of the data o users.

**Noted**

**Comment by MehtabAsHellic** [comment]
![lgoooo](https://github.com/Sayak-Bhunia/mystory/assets/101495398/537d824c-7b5b-4814-aee8-ec867c980ab6)
Have a look

**Comment by MehtabAsHellic** [comment]
![Demo1](https://github.com/Sayak-Bhunia/mystory/assets/101495398/e1da8ca4-063f-4c83-a522-5ce3c29a4501)
![Demo2](https://github.com/Sayak-Bhunia/mystory/assets/101495398/8213ef2b-6789-445e-a2f2-9629ebcce235)

Please have a look

**Comment by MehtabAsHellic** [comment]
![Demo1](https://github.com/Sayak-Bhunia/mystory/assets/101495398/c14e8361-ea07-41c5-b7e5-22495795923d)
![Demo3](https://github.com/Sayak-Bhunia/mystory/assets/101495398/71a1c62b-3b48-4ccf-9f3e-085bbe7e14e9)
![Demo4](https://github.com/Sayak-Bhunia/mystory/assets/101495398/eb492199-e2b1-49c3-9055-85b2e8af668f)

Please Have A Look

**Comment by Sayak-Bhunia** [comment]
the 2nd one looks good change the lock clor and also try to choose a more minimal font like the ones people use on studygrams on instagram.

**Comment by MehtabAsHellic** [comment]
![StylesDESIGN](https://github.com/Sayak-Bhunia/mystory/assets/101495398/a9c83e82-6ee4-41e6-8c1a-100a8395123b)

@Sayak-Bhunia Updated as you mentioned choosing a more minimal font style, similar to those used on "studygrams" on Instagram and showing you sum color options please select the font and color. So I can finalized this.

**Comment by Sayak-Bhunia** [comment]
Last one looks good.

**Comment by MehtabAsHellic** [comment]
> Last one looks good.

should I put in the public folder the svg

**Comment by MehtabAsHellic** [comment]
> Last one looks good.

![logostyle](https://github.com/Sayak-Bhunia/mystory/assets/101495398/2c20b426-6719-4a22-b608-a6761333494b)


logo style preference ?

**Comment by MehtabAsHellic** [comment]
> > > Last one looks good.
> > 
> > 
> > ![logostyle](https://private-user-images.githubusercontent.com/101495398/333654461-2c20b426-6719-4a22-b608-a6761333494b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MTYyMjgsIm5iZiI6MTcxNjYxNTkyOCwicGF0aCI6Ii8xMDE0OTUzOTgvMzMzNjU0NDYxLTJjMjBiNDI2LTY3MTktNGEyMi1iNjA4LWE2NzYxMzMzNDk0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQwNTQ1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zM2E0YjliNDEzNDJhY2UyYmFkZGExNzQ4NDUyZDQ4YjQwMGFlYjliMTk1MjJlYjgxYmZiOTdmYzRiMDI0ZWZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cP_6_v4NWKhBUdedhGJyQciPSdYe-RXrAYR6iEYU0vc)
> > Lock style preference ?
> 
> First one

ok will PR in the public folder

**Comment by MehtabAsHellic** [comment]
[](https://github.com/Sayak-Bhunia/mystory/pull/159)
[](https://github.com/MehtabAsHellic/mystory)

please merge and confirm

I add the svg in the public folder
