### ISSUE TITLE
Feat: Workflow for Autocommenting when a PR is merged

### ISSUE THREAD

**Issue by Asymtode712** [Sayak-Bhunia/mystory#144]
### Describe the feature

This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks

### Add ScreenShots

![PR merged](https://github.com/Sayak-Bhunia/mystory/assets/115717746/e7003237-4ec5-4b78-a60e-0c0acf8df20c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@Sayak-Bhunia please assign me this issue under gssoc'24

**Comment by Sayak-Bhunia** [comment]
> @Sayak-Bhunia please assign me this issue under gssoc'24

assigned.

**Comment by Asymtode712** [comment]
@Sayak-Bhunia I can modify the greetings as currently it only autocomments when the user creates his first issue or PR, I can add a workflow where comments will be added for each issue and PR created

**Comment by Asymtode712** [comment]
@Sayak-Bhunia Should i open these two issues?

**Comment by Sayak-Bhunia** [comment]
yes.
