### ISSUE TITLE
Feat: Workflow for Closing Old Issues

### ISSUE THREAD

**Issue by Asymtode712** [Sayak-Bhunia/mystory#145]
### Describe the feature

This feature aims to automate the process of managing old issues, ensuring that the repository remains organized and focused on relevant tasks. By automatically closing old issues, it reduces manual overhead for repository maintainers and helps keep the issue tracker tidy and up-to-date.

### Add ScreenShots

![Close Old Iss](https://github.com/Sayak-Bhunia/mystory/assets/115717746/37148393-46a3-4174-9ff2-8b4c08bf7ea1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@Sayak-Bhunia please assign me this issue under gssoc'24

**Comment by Sayak-Bhunia** [comment]
> @Sayak-Bhunia please assign me this issue under gssoc'24

assigned.
