### ISSUE TITLE
Feat: Workflow for closing Old PRs 

### ISSUE THREAD

**Issue by Asymtode712** [Sayak-Bhunia/mystory#146]
### Describe the feature

This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

### Add ScreenShots

![Close Old PRs](https://github.com/Sayak-Bhunia/mystory/assets/115717746/04d21492-9bde-445c-9fcf-da56881e38ef)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@Sayak-Bhunia please assign me this issue

**Comment by Sayak-Bhunia** [comment]
assigned.
