### ISSUE TITLE
Feat: Auto Commenting when an Issue is Closed

### ISSUE THREAD

**Issue by Asymtode712** [Sayak-Bhunia/mystory#147]
### Describe the feature

This feature aims to solve the problem of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts. This helps maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.

### Add ScreenShots

![issue closed](https://github.com/Sayak-Bhunia/mystory/assets/115717746/9d885344-d2bd-41e6-be6d-9cfd234b1cac)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@Sayak-Bhunia please assign me this issue

**Comment by Sayak-Bhunia** [comment]
assigned.
