### ISSUE TITLE
Add a current location string in the footer 

### ISSUE THREAD

**Issue by Sayak-Bhunia** [Sayak-Bhunia/mystory#15]
Add a current location string in the footer that will show the user's current location take inspiration from rauno.me 's portfolio website.

**Comment by psidh** [comment]
Can I work on this sir?

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by Sayak-Bhunia** [comment]
any updates ?

**Comment by psidh** [comment]
working on it, watching out for apis

**Comment by psidh** [comment]
Fixed by #45

**Comment by Kritika30032002** [comment]
@Sayak-Bhunia add labels
