### ISSUE TITLE
Feat: Displaying content on hoveing on FAQ page and enhancing its look

### ISSUE THREAD

**Issue by Asymtode712** [Sayak-Bhunia/mystory#156]
### Describe the feature

Currently, the contents of the three divs on FAQ page is displayed on clicking the down arrow button, I would like to display this content when a mouse is hovered over each of these divs and also improve the UI for each div.

### Add ScreenShots

![faq](https://github.com/Sayak-Bhunia/mystory/assets/115717746/b44a1bbc-3767-46de-9ec5-4f610c806924)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@Sayak-Bhunia please assign me this issue

**Comment by Kritika30032002** [comment]
@Asymtode712 updates?

**Comment by Asymtode712** [comment]
@Kritika30032002 Working on it will raise a PR for it by today

**Comment by Kritika30032002** [comment]
@Asymtode712 It has been 2 days

**Comment by Asymtode712** [comment]
@Kritika30032002 @Sayak-Bhunia Sorry for delaying the PR for long time, I have raised the PR, please review and merge it
