### ISSUE TITLE
Update greetings.yml

### ISSUE THREAD

**Issue by suhanipaliwal** [Sayak-Bhunia/mystory#158]
Currently when a person opens a new issue or pull request for the first time the message which is displayed doesn't seem very appropriate. It just shows "Message that will be displayed on users' first pull request" or "Message that will be displayed on users' first issue". I think the message should be a bit more welcoming. The issue message could maybe thank the contributor for pointing it out and the pr message should thank the contributor for contributing.

Could you please assign me this issue under GSSOC'24.

**Comment by Sayak-Bhunia** [comment]
> Currently when a person opens a new issue or pull request for the first time the message which is displayed doesn't seem very appropriate. It just shows "Message that will be displayed on users' first pull request" or "Message that will be displayed on users' first issue". I think the message should be a bit more welcoming. The issue message could maybe thank the contributor for pointing it out and the pr message should thank the contributor for contributing.
> 
> Could you please assign me this issue under GSSOC'24.

do Star the repo.
