### ISSUE TITLE
Create the about page

### ISSUE THREAD

**Issue by Sayak-Bhunia** [Sayak-Bhunia/mystory#16]
Create the about page and link it with the navbar.

**Comment by TenzDelek** [comment]
can i work in it

**Comment by Sayak-Bhunia** [comment]
assigned.
do star the repo.

**Comment by Sayak-Bhunia** [comment]
> do we have to write the content in the about or just have to create the route and link it to nav? @Sayak-Bhunia

yes you have to write the content describing the problem it solves that is being anonymous and use framer motion or gsap.

**Comment by TenzDelek** [comment]
got it!!

**Comment by Sayak-Bhunia** [comment]
The resume button that u have on your portfolio looks very good can you implement that to something here ?

**Comment by rishyym0927** [comment]
Hi @Sayak-Bhunia 

I want to work on this issue under GSSOC24. Please assign it to me.

Thanks

**Comment by Sayak-Bhunia** [comment]
> Hi @Sayak-Bhunia
> 
> I want to work on this issue under GSSOC24. Please assign it to me.
> 
> Thanks

@TenzDelek is already working on this issue does not raise a PR within 5 days then I will assign this issue to you.

**Comment by TenzDelek** [comment]
> The resume button that u have on your portfolio looks very good can you implement that to something here ?

sure

**Comment by TenzDelek** [comment]
let me finish the pending issue and i will implement that next

**Comment by Sayak-Bhunia** [comment]
any updates ?

**Comment by Vaibhavsg17** [comment]
Hello @TenzDelek & @Sayak-Bhunia 
I want to add GitHub globe to the About Page &  home page is already filled. i requests @TenzDelek to leave about hero section for me and start developing other stuff.

My suggested Workflow:

![image](https://github.com/Sayak-Bhunia/mystory/assets/66477893/c48729cc-8139-4c16-a2ff-37e088ea0985)

**Comment by Sayak-Bhunia** [comment]
I want the globe to be at the end of the website

**Comment by TenzDelek** [comment]
> Hello @TenzDelek & @Sayak-Bhunia 
> 
> I want to add GitHub globe to the About Page &  home page is already filled. i requests @TenzDelek to leave about hero section for me and start developing other stuff.
> 
> 
> 
> My suggested Workflow:
> 
> 
> 
> ![image](https://github.com/Sayak-Bhunia/mystory/assets/66477893/c48729cc-8139-4c16-a2ff-37e088ea0985)
> 
> 

@Vaibhavsg17 sure, looks good to me,once yours pr is merge ping me. Will do my part after that. @Sayak-Bhunia sorry for delay , was traveling for few days, will start working on it as soon as possible.

**Comment by Vaibhavsg17** [comment]
from a UI design perspective, Globe is an attractive element of the website placing it in the hero section will 
excite User and it will also convey the indirect message that MYStory is used globally.

**Comment by Vaibhavsg17** [comment]
> I want the globe to be at the end of the website

from a UI design perspective, Globe is an attractive element of the website placing it in the hero section will
excite User and it will also convey the indirect message that MYStory is used globally.

**Comment by Vaibhavsg17** [comment]
> > Hello @TenzDelek & @Sayak-Bhunia
> > I want to add GitHub globe to the About Page &  home page is already filled. i requests @TenzDelek to leave about hero section for me and start developing other stuff.
> > My suggested Workflow:
> > ![image](https://private-user-images.githubusercontent.com/66477893/329934997-c48729cc-8139-4c16-a2ff-37e088ea0985.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1Nzk5NzksIm5iZiI6MTcxNTU3OTY3OSwicGF0aCI6Ii82NjQ3Nzg5My8zMjk5MzQ5OTctYzQ4NzI5Y2MtODEzOS00YzE2LWEyZmYtMzdlMDg4ZWEwOTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA1NTQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNjMyZGQwNzRhZTRjNjk5YTJlMmIwODlhZGJkZTZmZjRiZDUyNmQ2YmU3NmEwYzAxOWIyODQ5YTUzZThiMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NDV5X1XLfbIJcG6-J-z51q1DfLG-cweGhMD1iCC8SKI)
> 
> @Vaibhavsg17 sure, looks good to me,once yours pr is merge ping me. Will do my part after that. @Sayak-Bhunia sorry for delay , was traveling for few days, will start working on it as soon as possible.

@TenzDelek Sure, i will create About page and add my globe component then you start adding your components below, i will ping you once my pr is merge
