### ISSUE TITLE
Create the FAQ's page

### ISSUE THREAD

**Issue by Sayak-Bhunia** [Sayak-Bhunia/mystory#17]
Create the FAQ's page and link it with the navbar.

**Comment by TenzDelek** [comment]
can i work on it too

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by Sayak-Bhunia** [comment]
do star the repo.

**Comment by TenzDelek** [comment]
ok

**Comment by rishyym0927** [comment]
Hi @Sayak-Bhunia 

I want to work on this issue under GSSOC24. Please assign it to me.

Thanks

**Comment by Sayak-Bhunia** [comment]
> Hi @Sayak-Bhunia
> 
> I want to work on this issue under GSSOC24. Please assign it to me.
> 
> Thanks

@TenzDelek is already working on this issue if he does not raise a PR within 5 days then I will assign this issue to you @rishyym0927 .
