### ISSUE TITLE
Feat: Add a star us on github button on the landing page

### ISSUE THREAD

**Issue by Sayak-Bhunia** [Sayak-Bhunia/mystory#170]
### Describe the feature

Add a star us on github button on the landing page like this one on timely

### Add ScreenShots

![image](https://github.com/Sayak-Bhunia/mystory/assets/110457746/dec0d802-6a34-4d0b-871b-07ec39eedb5d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by TenzDelek** [comment]
@Sayak-Bhunia would love to work on this as well
