### ISSUE TITLE
BUG: Fix the profile page

### ISSUE THREAD

**Issue by Sayak-Bhunia** [Sayak-Bhunia/mystory#174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Fix the profile page
this error is showing
![image](https://github.com/Sayak-Bhunia/mystory/assets/110457746/407131f3-729e-4202-bb3a-d0613e694fad)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by TenzDelek** [comment]
this is also related with the database, null  value are being passed which is breaking this

**Comment by Tomkndn** [comment]
I want to work on this project. Kindly assign this issue to me. So that I can start working on this task.
