### ISSUE TITLE
Create the Share and Confession page using a DB

### ISSUE THREAD

**Issue by Sayak-Bhunia** [Sayak-Bhunia/mystory#18]
You can use Supabase or mongoDB.

**Comment by psidh** [comment]
Can I work on this sir, I have 1 year of experience on MongoDB and Next.js Framework, I believe I can do justice to this feature

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by psidh** [comment]
## Update

used `MongoDB` and added `users` data mapped to the `confessions` in an array

### Preview

`Features Implemented`
- Adding a `confession`
- Retrieving a `confession` using a username

https://github.com/Sayak-Bhunia/mystory/assets/116720762/69299b7b-5f91-4fc1-a40a-e808f569f309

**Comment by psidh** [comment]
One issue will come during deployment because I have to share the .env.local variable that is MONGODB_URI with you , once let me know, I will share that in your Insta DM maybe

**Comment by Sayak-Bhunia** [comment]
looks good do the needful 
insta - https://www.instagram.com/raw_shots29/
whatsapp - 8017829475
you can also reach out to me on discord - sayak2903
mail - sbhunia2903@gmail.com
just let me know where you will be sending though :)

**Comment by psidh** [comment]
I would mail the env 👍🏼

**Comment by Sayak-Bhunia** [comment]
ig the fetching is not working properly ?

**Comment by psidh** [comment]
I just tried , it worked fine for me, maybe try to search the actual username from where the confession has happened

**Comment by Sayak-Bhunia** [comment]
It works with ***sidharth*** any username other than that is not working.

**Comment by Sayak-Bhunia** [comment]
I just checked now it is working fine.
