### ISSUE TITLE
Feat: Bring the star us on github button below the tag line

### ISSUE THREAD

**Issue by Sayak-Bhunia** [Sayak-Bhunia/mystory#180]
### Describe the feature

place the button below the tagline "a way to share stories anonymously".

### Add ScreenShots

![image](https://github.com/Sayak-Bhunia/mystory/assets/110457746/26064270-b407-44ea-aacd-5b04b4e4cd9c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by TenzDelek** [comment]
@Sayak-Bhunia  would love to work on this!!
