### ISSUE TITLE
Bug: making all the UI Consistent 

### ISSUE THREAD

**Issue by TenzDelek** [Sayak-Bhunia/mystory#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Currently the website lacks a consistent look whether it be a form or a card. Creating a overall improved UI that matches the home page

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sayak-Bhunia** [comment]
no
