### ISSUE TITLE
Feat:About page 3D Demo

### ISSUE THREAD

**Issue by Aksshay88** [Sayak-Bhunia/mystory#197]
### Describe the feature

@Sayak-Bhunia   As Mentioned in the prev improvements I have improved the website according to your suggestion pls do look at this 

![image](https://github.com/Sayak-Bhunia/mystory/assets/119944779/1d129f39-c3cd-4d33-84df-ffd90e2f9440)

If required will add an extra details .

Pls do assign the GSSOC label .(Level 3)

Thanks in advance

### Add ScreenShots

![image](https://github.com/Sayak-Bhunia/mystory/assets/119944779/619ec912-8337-48d6-8a48-78f6a9ea1812)

This is the image for the about page 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sayak-Bhunia** [comment]
no its not looking good you should try making it like this 
![image](https://github.com/Sayak-Bhunia/mystory/assets/110457746/e860fd6f-66de-4d19-9226-51bce4044066)
on the left side there will be info about how i started making mystory and on the bottom there should be a place showing the github usernames of all the contributers @Sayak-Bhunia in this format take a look at the new nextjs15 blog
![image](https://github.com/Sayak-Bhunia/mystory/assets/110457746/ceec5a9b-434a-4288-913f-4f8767cce1e0)
and the usernames should work like a button to their respective github accounts

**Comment by Aksshay88** [comment]
@Sayak-Bhunia Yeah sure will work towards it 
Thanks in advance

**Comment by Kritika30032002** [comment]
@Aksshay88 updates?

**Comment by Aksshay88** [comment]
@Kritika30032002 yeah actually working towards it
