### ISSUE TITLE
BUG: After user login, the whole navbar does not fit the screen

### ISSUE THREAD

**Issue by ayush-848** [Sayak-Bhunia/mystory#200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The confess button is not totally present to the visible screen

![image](https://github.com/Sayak-Bhunia/mystory/assets/126975547/a04a0020-fd64-47d3-9a6e-f14ed4684a81)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayush-848** [comment]
Hello @Sayak-Bhunia please assign this issue to me.

**Comment by ayush-848** [comment]
@Sayak-Bhunia 
![image](https://github.com/Sayak-Bhunia/mystory/assets/126975547/aaf8297e-cec3-4ae3-8cf2-0b3871ece3ec)
Signin and signup both not happening

**Comment by Sayak-Bhunia** [comment]
fix that.

**Comment by ayush-848** [comment]
@Sayak-Bhunia My laptop is a bit larger than normal so this issue was present 
when I tried to open it with a normal 1280px screen, it was ok.
