### ISSUE TITLE
Feat: Create a Contributors page

### ISSUE THREAD

**Issue by Vaibhavsg17** [Sayak-Bhunia/mystory#209]
### Describe the feature

- This is an entirely open-source project so we create a contributor page 
- This page will show that we respect our contributors & give them proper credit.
- 1. Creator (here will come your profile) 
-  2. Meet our Contributors (here comes the developer who is contributing to the mystory)

### Add ScreenShots

just reference image
![image](https://github.com/Sayak-Bhunia/mystory/assets/66477893/deebf3be-0c7f-4062-8cd5-bd3a0ed0de17)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vaibhavsg17** [comment]
@sanjay-kv please assign me this

**Comment by Sayak-Bhunia** [comment]
can you make it like this
![image](https://github.com/Sayak-Bhunia/mystory/assets/110457746/b827501d-fe28-4988-9851-d96edaeabd4f)
all the usernames of the contributors will be shown on the website in the same manner given here but the usernames should also work as links/button to their respective github profiles
