### ISSUE TITLE
BUG: fixing the home page 

### ISSUE THREAD

**Issue by TenzDelek** [Sayak-Bhunia/mystory#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

<img width="882" alt="image" src="https://github.com/Sayak-Bhunia/mystory/assets/122612557/36fd1777-f892-4678-aeb2-046af0c5b483">
the current layout of this in the homepage is not neccesary here, we can put this section in the about page. 
propose to move the existing developer section in the about page as it make more sense. 
also fixing the layout whitespace

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shweta-281** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me?
