### ISSUE TITLE
BUG: Sign Up problem with github

### ISSUE THREAD

**Issue by ayush-848** [Sayak-Bhunia/mystory#213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Sayak-Bhunia/mystory/assets/126975547/f7331ada-58bd-428d-a28c-031aac7c2dbb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayush-848** [comment]
@Sayak-Bhunia I solved this part though. Assign this issue to me so that I can make give the PR

**Comment by Sayak-Bhunia** [comment]
it is working fine
