### ISSUE TITLE
Sticky navbar and add smooth scroll feature using lenis

### ISSUE THREAD

**Issue by siddxharth1** [Sayak-Bhunia/mystory#23]
We can add smooth scrolling using lenis and make the navbar sticky so that it is accessible from wherever.
Can you please assign me this task under gssoc

**Comment by psidh** [comment]
Issue: #9 solves this

**Comment by Sayak-Bhunia** [comment]
> We can add smooth scrolling using lenis and make the navbar sticky so that it is accessible from wherever. Can you please assign me this task under gssoc

Issue #9 already solves this you can work on some other issue.
