### ISSUE TITLE
Feat: I have included the Small selection of your profile in the about page

### ISSUE THREAD

**Issue by Aksshay88** [Sayak-Bhunia/mystory#235]
### Describe the feature

I have included this in the 3d pin componenet from the aceternity UI where the user could see more about you in the profile page 

### Add ScreenShots

![image](https://github.com/Sayak-Bhunia/mystory/assets/119944779/9b02d5fd-5158-428c-9c41-5cfea4e858f3)

https://github.com/Sayak-Bhunia/mystory/assets/119944779/2e5b387e-2c2c-4c6f-b85f-221b736a671a

@Sayak-Bhunia pls do add the GSSOC Label .

Thanks in advance. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kritika30032002** [comment]
about section includes info about the project not the repo owner

**Comment by Aksshay88** [comment]
@Kritika30032002 will change this one and update

**Comment by Kritika30032002** [comment]
closing this pr
also about section is assigned to someone else
