### ISSUE TITLE
BUG:about page missing

### ISSUE THREAD

**Issue by Varsani2520** [Sayak-Bhunia/mystory#237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

here in about route there is nothing instead of about title:
![image](https://github.com/Sayak-Bhunia/mystory/assets/137641079/7f9f633c-2343-4b56-94a1-3fd337a31b2b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kritika30032002** [comment]
duplicate issue
