### ISSUE TITLE
BUG:faq page collapse not working correctly

### ISSUE THREAD

**Issue by Varsani2520** [Sayak-Bhunia/mystory#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

issue is button click then open the description but when i re click then not close :
![image](https://github.com/Sayak-Bhunia/mystory/assets/137641079/285e1bcf-7ee3-480e-96eb-9083f683b476)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kritika30032002** [comment]
solved in recent pr
