### ISSUE TITLE
Consistent Branding: Add Footer to All Pages & Enhance Header

### ISSUE THREAD

**Issue by piyush-gambhir** [Sayak-Bhunia/mystory#24]
To strengthen our website's branding and improve user navigation, we need to add a consistent footer to all pages and refine the existing header.

Currently, our website lacks a footer, missing an opportunity to provide essential information and navigation links. Additionally, the current header could be improved to better guide users and showcase our brand identity.

I would want to work on this issue.

**Comment by psidh** [comment]
#6  
#9

solves this

**Comment by Sayak-Bhunia** [comment]
Issue #6 and #9 already solves this
