### ISSUE TITLE
Add a scroll neon light effect on both the sides

### ISSUE THREAD

**Issue by Sayak-Bhunia** [Sayak-Bhunia/mystory#25]
here's an example sonicrypt.vercel.app
he has used blue but you need to use violet neon color

**Comment by Vaibhavsg17** [comment]
I like to work on this issue, assign this to me

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by Vaibhavsg17** [comment]
@Sayak-Bhunia Thankyou , Also add the level tag

**Comment by Sayak-Bhunia** [comment]
what level ?

**Comment by Vaibhavsg17** [comment]
tag used to give points.
example - level1, level2, level3

**Comment by Sayak-Bhunia** [comment]
okay.

**Comment by Sayak-Bhunia** [comment]
do star the repo.

**Comment by Sayak-Bhunia** [comment]
use acernity ui for this

**Comment by Vaibhavsg17** [comment]
> use acernity ui for this

Sure

**Comment by Sayak-Bhunia** [comment]
Any updates?

**Comment by Vaibhavsg17** [comment]
Done

**Comment by Sayak-Bhunia** [comment]
merged.
