### ISSUE TITLE
Feat: Add About Us page

### ISSUE THREAD

**Issue by Tanishka023** [Sayak-Bhunia/mystory#258]
### Describe the feature

The current site includes an About us page which looks like this -

![image](https://github.com/Sayak-Bhunia/mystory/assets/120386924/160c87e2-42b0-4370-a80d-854de9bab518)
I want to make an About us page for the site

### Add ScreenShots
CURRENT -
![image](https://github.com/Sayak-Bhunia/mystory/assets/120386924/24e47c09-1f3e-4e65-bd78-e5fff76cb52b)
UPDATED -
![image](https://github.com/Sayak-Bhunia/mystory/assets/120386924/1cf10406-848b-4a4b-8d3d-17c3a4c038a5)

will add names of Project admins and contributers, mission and values

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kritika30032002** [comment]
duplicate #247
