### ISSUE TITLE
Feat: Adding "ABOUT " page ( currently its blank)

### ISSUE THREAD

**Issue by HarshitGupta1511** [Sayak-Bhunia/mystory#264]
### Describe the feature

I want to add ABOUT page and add proper content about the project by adding separate about.html,about.css files.

please assign this task to me @saya

### Add ScreenShots

<img width="1440" alt="Screenshot 2024-06-22 at 10 38 04 PM" src="https://github.com/Sayak-Bhunia/mystory/assets/120268295/b1279d59-1079-4d52-b18f-85fe87ff907e">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by komal-agarwal5** [comment]
@Kritika30032002 Hey no hard feelings but just had a doubt as I had raised an issue for about page #247 much before this one was raised and you simply closed it and are assigning the same task to someone who has raised it much later than mine, was their any problem in my issue?

**Comment by Kritika30032002** [comment]
duplicate #247
