### ISSUE TITLE
Improving The Navbar With Better Minimalistic Design and Fonts

### ISSUE THREAD

**Issue by rishyym0927** [Sayak-Bhunia/mystory#28]
Hi @Sayak-Bhunia 

The current navbar design lacks a minimalistic aesthetic and utilizes fonts that may not align with the desired style. To enhance the user experience and achieve a cleaner, more modern look, we aim to revamp the navbar with a focus on minimalistic design principles and appropriate font choices.

I want to work on this issue myself.

Thanks

**Comment by rishyym0927** [comment]
Hi I want to work on this under GSSOC24

**Comment by psidh** [comment]
#9

solves this
