### ISSUE TITLE
Footer links are dysfunctional and lack aesthetically pleasing design.

### ISSUE THREAD

**Issue by rishyym0927** [Sayak-Bhunia/mystory#29]
Hi @Sayak-Bhunia 

I want to mention that footer links are not working. We can improve this easily and the scope of design can be increased. 
I want to work on this issue myself

Thanks

**Comment by rishyym0927** [comment]
Hi, I want to work on this issue Please assign under GSSOC24

thanks

**Comment by Sayak-Bhunia** [comment]
assigned.
please provide a better minimal design for the footer.

**Comment by Sayak-Bhunia** [comment]
closed.
