### ISSUE TITLE
The error page can undergo modifications to align with improved minimalistic styles.

### ISSUE THREAD

**Issue by rishyym0927** [Sayak-Bhunia/mystory#30]
Hi @Sayak-Bhunia 

The error page can be updated to reflect a more minimalistic design approach. I want to work on this myself

Thanks

**Comment by rishyym0927** [comment]
Hi,

I want to work on this myself under GSSOC 24
Thanks

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by Sayak-Bhunia** [comment]
Any updates?

**Comment by Kritika30032002** [comment]
@rishyym0927 Any updates?

**Comment by TenzDelek** [comment]
@Sayak-Bhunia  is this still relevant? if yes, would like to do this
