### ISSUE TITLE
Add box background from Acernity UI

### ISSUE THREAD

**Issue by Sayak-Bhunia** [Sayak-Bhunia/mystory#35]
You have to use acernity UI and add the box background.

**Comment by psidh** [comment]
I would like to work on it

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by psidh** [comment]
## Current Implementation


https://github.com/Sayak-Bhunia/mystory/assets/116720762/41d6fee1-00fa-4f9b-8a7b-aeff0cdb31c3

**Comment by Sayak-Bhunia** [comment]
Looks good please adjust the width of some components as they are not responsive.

**Comment by psidh** [comment]
Is this fine?

https://github.com/Sayak-Bhunia/mystory/assets/116720762/35e16eab-39fb-4aef-aa77-9468fb0ef3c4

**Comment by Sayak-Bhunia** [comment]
U see the components from acernity ui are slightly on the right side

**Comment by psidh** [comment]
Oh okay okay

**Comment by psidh** [comment]
## I have fixed the spacing

> (maybe box layout may give a feel that the components are not aligned)

<img width="434" alt="Screenshot 2024-05-12 at 10 25 32" src="https://github.com/Sayak-Bhunia/mystory/assets/116720762/d898e515-174c-4b17-8510-60a196e25754">


<img width="435" alt="Screenshot 2024-05-12 at 10 25 21" src="https://github.com/Sayak-Bhunia/mystory/assets/116720762/e505fe96-33b0-4f85-b10e-fe6472b19247">




<img width="434" alt="Screenshot 2024-05-12 at 10 25 07" src="https://github.com/Sayak-Bhunia/mystory/assets/116720762/69148e45-20cf-44a1-a104-8ca80b288020">

**Comment by psidh** [comment]
https://github.com/Sayak-Bhunia/mystory/assets/116720762/f3062fe7-2ae9-4fc2-965b-be30024a08ca

**Comment by Sayak-Bhunia** [comment]
merged.
