### ISSUE TITLE
[Feature]: To Develop Share Functionality 

### ISSUE THREAD

**Issue by Vaibhavsg17** [Sayak-Bhunia/mystory#37]
I would like to develop Share Functionality which allows users to share their stories on other social media sites

- assign this to me

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by mohdjami** [comment]
If this issue is not resolved, @Sayak-Bhunia assign it to me.

**Comment by Sayak-Bhunia** [comment]
> If this issue is not resolved, @Sayak-Bhunia assign it to me. I will implement the share functionality. I will just need some more light on the topic how you want it to be implemented.
> For eg. If you just want a custom link or share on whatsapp, insta etc.

assigned.
Idea - there should be a button for Twitter to share the story of possible means if the number of word are in a certain limit as Twitter allows.
