### ISSUE TITLE
Add authentication 

### ISSUE THREAD

**Issue by Sayak-Bhunia** [Sayak-Bhunia/mystory#4]
You can use authjs or nextJS auth or any open source authentication tech like auth0, firebase

**Comment by abir446** [comment]
### I will use Authjs for authentication
_I would like to work on this issue by creating a session from authjs and providing authentication from google and_
_github providers_

**Comment by Sayak-Bhunia** [comment]
> I would like to work on this issue, please assign it to me.

@abir446 is already working on this issue if he's unable to raise a PR within 5 days then I will assign this issue to you.

**Comment by abir446** [comment]
@Sayak-Bhunia Where do you want the sign up button. in the nabvar or in the hero section,. If you want it in the navbar, I have to change files in navbar too.

**Comment by Sayak-Bhunia** [comment]
In navbar

**Comment by abir446** [comment]
https://github.com/Sayak-Bhunia/mystory/assets/108267299/fce20096-f69b-4e32-bf00-f8dfbbe9c81b
### Current Progress
@Sayak-Bhunia I have progressed this much. Please share thoughts about this. I will change the login with github button styling later, I ami currently testing its functionality. Also, I changed, the 'a' tags from Navbar component, as a result, the page is not reloading every time when something is clicked.
### Doubts
_What content should be in the  user profile page? I will need that user profile page for sign out as all other pager are client side_
_Therefore, suggest some content to show on the user profile page. It will be shown when the user click on his/her name._

**Comment by Sayak-Bhunia** [comment]
Looks really good.
The content should profile picture, name and whatever u suggest.

**Comment by abir446** [comment]
@psidh Hey, can you help me on this issue? I have created authentication with auth js providers of google and github. This is working fine in my system, but when I create a PR, it says deployment failed. What can be the possible reasons?

**Comment by psidh** [comment]
1. Maybe there are `merge conflics` with your branch and the adjacent branch, you can clear those in your editor locally (this happened to be also, mentor asked me to fix this, it was done )

2. It can be that, Server Side rendering has failed due to user actions on a button or a react hook 

3. Maybe mentor can shed more light as he is the admin on vercel, maybe he will have some logs on vercel side.

Once wait and let mentor convey his message, it will be resolved.

**Comment by psidh** [comment]
If there is anything I can do it help you can ask @abir446 ✅

**Comment by mohdjami** [comment]
Hi @Sayak-Bhunia, I think this issue is not resolved yet. I can make raise a PR making complete login and signup functionality in one day using next-auth library. Please assgn this issue to me.

**Comment by Sayak-Bhunia** [comment]
> Hi @Sayak-Bhunia, I think this issue is not resolved yet. I can raise a PR making complete login and signup functionality in one day using next-auth library. Please assgn this issue to me. 

assigned.

**Comment by mohdjami** [comment]
Thanks @Sayak-Bhunia for assigning, I have completed the backend part. Some work is left on the frontend signin and sign out pages. I will raise a PR today only.

**Comment by mohdjami** [comment]
Hey @Sayak-Bhunia, I have implemented Login functionality successfully. Please review my PR and let me know if any changed needs to be done. Looking for a response.

https://github.com/Sayak-Bhunia/mystory/assets/114595881/29aec4d0-d093-4eec-9afa-02658c749797

**Comment by mohdjami** [comment]
Hey @Sayak-Bhunia, as this PR is closed there are some issues like on the cofessions page. I have fixed those issues should I create a new issue and raise a PR? Please answer. After merging that pull request everything will be working perfectly. I have build application locally and had no errors.

**Comment by Sayak-Bhunia** [comment]
Please raise a pr asap.

**Comment by mohdjami** [comment]
Sure, I have fixed the issue. I will create a new issue for that with linked PR in a minute. Please label that issue under GSSoC'24.

**Comment by mohdjami** [comment]
> Please raise a pr asap.

Done #95 Please label the issue and merge the PR.
Regards
