### ISSUE TITLE
[Bug]: Fix the alignment of the website for both small and large screens

### ISSUE THREAD

**Issue by Sayak-Bhunia** [Sayak-Bhunia/mystory#42]

**Comment by psidh** [comment]
I would like to work on this sir.

**Comment by rishyym0927** [comment]
Hi @Sayak-Bhunia ,
I want to work on this issue

**Comment by Sayak-Bhunia** [comment]
> Hi @Sayak-Bhunia ,
> I want to work on this issue

assigned.

**Comment by Kritika30032002** [comment]
@Sayak-Bhunia add labels
