### ISSUE TITLE
Add cursor animation

### ISSUE THREAD

**Issue by Sayak-Bhunia** [Sayak-Bhunia/mystory#5]
add a cool cursor animation you can get inspiration from the take inspiration from awwwards.com

**Comment by suraj-9849** [comment]
I would like to work on this I can make the cool cursor that is inspired from the awwwards.com. So can you please assign this to me under @GSSOC'24 @Sayak-Bhunia

**Comment by Sayak-Bhunia** [comment]
the issue is assigned to you.

**Comment by Sayak-Bhunia** [comment]
do star the repo and send a design before implementing.

**Comment by Sayak-Bhunia** [comment]
any updates ?

**Comment by suraj-9849** [comment]
yeah sir I am using the gsap for this.

**Comment by Sayak-Bhunia** [comment]
okay do give me a pre deployment design.

**Comment by suraj-9849** [comment]
![image](https://github.com/Sayak-Bhunia/mystory/assets/146669517/aef6544d-fc62-45c8-88e6-7853b2641d2b)
I saw this premium good looking cursor in many website and STOD(site of the day) also has the same I am using this is it ok

**Comment by suraj-9849** [comment]
I will be making it smooth

**Comment by Sayak-Bhunia** [comment]
Yeah it's good but you should change the colors to the ones that are there in the website.

**Comment by suraj-9849** [comment]
Yeah sir I made the changes and created the PR you can see I also added the Locomotive.JS BETA-5 Version for the smooth scrolling of the website which can provide the best experience for the user. @Sayak-Bhunia Thank you for this opportunity

**Comment by Sayak-Bhunia** [comment]
the animation is good but see in todays site of the day the circle expands while hovering on the navbar so i want you to do that on the navbar as well as the text if possible
