### ISSUE TITLE
Navigation pages not working

### ISSUE THREAD

**Issue by AkhilaSunesh** [Sayak-Bhunia/mystory#55]
![image](https://github.com/Sayak-Bhunia/mystory/assets/140897461/2c09a825-274d-41a9-bb04-0e303127049b)
About page
FAQ's 
Share
Confess buttons don't seem to work
### 
**Allow me to resolve these issues**

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by Kritika30032002** [comment]
@AkhilaSunesh   Any updates?

**Comment by Kritika30032002** [comment]
@AkhilaSunesh It has been 2 weeks.
