### ISSUE TITLE
Add a time string in footer 

### ISSUE THREAD

**Issue by Sayak-Bhunia** [Sayak-Bhunia/mystory#6]
Using JavaScript you can do that.

**Comment by Kapil619** [comment]
Hi, @Sayak-Bhunia, I will work on this if you want . 
I am a  Fullstack developer with strong proficiency in NextJs as well as Javascript .
Please Assign it to me.
Best Regards.
Kapil

**Comment by Sayak-Bhunia** [comment]
the issue is assigned to you.
do star the repo.
send a design before implementing.

**Comment by Kapil619** [comment]
Hi @Sayak-Bhunia ,
I have completed the task, Please merge the PR and mark the issue as completed.
Thanks a lot for your co-operation throughout.
Best Regards.
Kapil

**Comment by Sayak-Bhunia** [comment]
Hy please add a glowing green circle on the left of the string.

**Comment by Kapil619** [comment]
> Hy please add a glowing green circle on the left of the string.

Okay will do that.
Any other improvements/suggestions?

**Comment by Kapil619** [comment]
> Hey please add a glowing green circle on the left of the string.

Completed the required task.

**Comment by Sayak-Bhunia** [comment]
merged!

> > Hey please add a glowing green circle on the left of the string.
> 
> Completed the required task.

merged!
