### ISSUE TITLE
[Enhancement] Docker and Docker-Compose files

### ISSUE THREAD

**Issue by MishraTanishq619** [Sayak-Bhunia/mystory#60]
This issue proposes the addition of Dockerfiles and Docker Compose configuration to streamline the deployment and development process of the project.

- [ ] Create Dockerfiles
- [ ] Implement Docker Compose
- [ ] Update ReadMe accordingly

**Comment by MishraTanishq619** [comment]
I would Like to work on this myself.
Please assign me this, for GSSOC.

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by psidh** [comment]
I would like to work on this if @MishraTanishq619 fails to make a PR, is that okay sir @Sayak-Bhunia ?

**Comment by MishraTanishq619** [comment]
@psidh , It's late for you. But you can help by reviewing my PR.
