### ISSUE TITLE
Mobile View Hamburger Menu Translation

### ISSUE THREAD

**Issue by Che140401** [Sayak-Bhunia/mystory#63]
**Desktop version view navbar**

Adding new feature navbar translate from  top

![Screenshot 2024-05-13 092016](https://github.com/Sayak-Bhunia/mystory/assets/109230049/a589741b-d78d-4088-9a70-0afc9a1d821a)

https://github.com/Sayak-Bhunia/mystory/assets/109230049/291210ec-3ba9-419c-91e2-f5afc6defa09

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by Sayak-Bhunia** [comment]
> **Desktop version view navbar**
> 
> Adding new feature navbar translate from  top
> 
> ![Screenshot 2024-05-13 092016](https://github.com/Sayak-Bhunia/mystory/assets/109230049/a589741b-d78d-4088-9a70-0afc9a1d821a)
> 
> 
> https://github.com/Sayak-Bhunia/mystory/assets/109230049/291210ec-3ba9-419c-91e2-f5afc6defa09
> 
> 

What u have done with the navbar ? It is working bro.
