### ISSUE TITLE
Text Alignment Broken 

### ISSUE THREAD

**Issue by Che140401** [Sayak-Bhunia/mystory#64]
**Text alignment broken**

We have to make text alignment properly suitable in all media screen from desktop to mobile 

**Tab version**

![Screenshot 2024-05-13 092445](https://github.com/Sayak-Bhunia/mystory/assets/109230049/4be23381-c670-460c-92d7-b0d87e7005aa)

**Mobile Version**

![Screenshot 2024-05-13 092518](https://github.com/Sayak-Bhunia/mystory/assets/109230049/0bf53958-2de7-4551-80cb-59a6c4456a44)

https://github.com/Sayak-Bhunia/mystory/assets/109230049/bf8c77e1-2cef-483b-96a0-fdcc4ccf3e61

**Tab-to-Mobile version**

https://github.com/Sayak-Bhunia/mystory/assets/109230049/55cef8e0-7154-4688-abdb-615e91623cd8

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by Sayak-Bhunia** [comment]
do star the repo

**Comment by Sayak-Bhunia** [comment]
merged.

**Comment by Sayak-Bhunia** [comment]
fixed no worries.
