### ISSUE TITLE
[FEATURE] Add an Accordion style in FAQ's page

### ISSUE THREAD

**Issue by AmitBiswas1402** [Sayak-Bhunia/mystory#65]
So now the About section is showing 404 not found, I would like to add an Accordion-style FAQs section

**Comment by AmitBiswas1402** [comment]
Hey @Sayak-Bhunia please assign this issue to me with the GSSOC'24 tag

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by Sayak-Bhunia** [comment]
do star the repo

**Comment by Kritika30032002** [comment]
@AmitBiswas1402  Any updates?

**Comment by AmitBiswas1402** [comment]
@Kritika30032002 I messaged @Sayak-Bhunia about the problems I am facing in this repo the theme has got to light while I was working with shadcn UI, that's why it is taking time...

**Comment by Kritika30032002** [comment]
@Sayak-Bhunia  Look into it.

**Comment by Sayak-Bhunia** [comment]
> @Sayak-Bhunia  Look into it.

I already did.
