### ISSUE TITLE
Profile View for the User .

### ISSUE THREAD

**Issue by Aksshay88** [Sayak-Bhunia/mystory#66]
I would like to add the forms components so that the user can could see the profile that he could have a preferance setting of his own so that it have a better option to add this component in the website .
![image](https://github.com/Sayak-Bhunia/mystory/assets/119944779/9d2e64bd-5832-42a2-853e-79b446354712)

I would like to work on this issue .
Thanks in advance.

**Comment by Aksshay88** [comment]
@Sayak-Bhunia I request you to add this under the label of gssoc so that my contribution will taken int account .
Thanks once again

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by Aksshay88** [comment]
okay

**Comment by Sayak-Bhunia** [comment]
do star the repo first

**Comment by Vdcds** [comment]
Hey @Sayak-Bhunia I would love to work on this issue  ... also I've noticed that the the UI on mobile is having extra dragabble width on some devices ... 
![image](https://github.com/Sayak-Bhunia/mystory/assets/161267137/c1abb4d7-933e-44e7-a7dc-b7159fe334a9)
is there an exisiting issue about that one ? If not I would love to work on making the site optimally responsive too

**Comment by Sayak-Bhunia** [comment]
> Hey @Sayak-Bhunia I would love to work on this issue  ... also I've noticed that the the UI on mobile is having extra dragabble width on some devices ... 
> ![image](https://github.com/Sayak-Bhunia/mystory/assets/161267137/c1abb4d7-933e-44e7-a7dc-b7159fe334a9)
> is there an exisiting issue about that one ? If not I would love to work on making the site optimally responsive too

Create an issue and then I will assign it to you and do star therepo first

**Comment by Kritika30032002** [comment]
@Aksshay88  any updates?

**Comment by mohdjami** [comment]
@Kritika30032002 and @Sayak-Bhunia Assign this issue to me. We need a profile page ASAP as we already have a settings page.
