### ISSUE TITLE
Add buy me a coffee hover button

### ISSUE THREAD

**Issue by Sayak-Bhunia** [Sayak-Bhunia/mystory#7]
hover button on the bottom right corner that stays till while scrolling.

**Comment by Kapil619** [comment]
Hi, @Sayak-Bhunia , I will work on this if you want .
I am a Fullstack developer with strong proficiency in NextJs as well as Javascript .
You can visit my portfolio website which is created in NextJs. https://kapilbadokar.vercel.app/
Please Assign this issue  to me.
Best Regards.
Kapil

**Comment by Sayak-Bhunia** [comment]
the issue is assigned to you.
do star the repo.
and send a design before implementing.

**Comment by Sayak-Bhunia** [comment]
any updates ?

**Comment by Kapil619** [comment]
> any updates ?

Hi @Sayak-Bhunia ,
Will begin the working shortly.
The task will be completed by midnight.
Thanks for understanding.
Best Regards.
Kapil

**Comment by Kapil619** [comment]
![coffee](https://github.com/Sayak-Bhunia/mystory/assets/84692375/c46acd94-c293-45a7-bed0-96f7cb38bf88)

Do you want it like this 

- It is fixed on the bottom of screen, and is completely visible while scrolling
- Also responsive on the mobile.
- When the user clicks , hes redirected to the buymeacoffee profile page of yours, which you will add.

**Comment by Sayak-Bhunia** [comment]
https://www.buymeacoffee.com/sbhunia2909 this is my buymeacoffe account add this link to the button and can you make the button round like only the coffee icon will be visible.

**Comment by Kapil619** [comment]
I have completed it .

- Updated it with your profile url.
- Made the icon circle.
- Added hover and on-Click effects

**Comment by Kapil619** [comment]
Hi @Sayak-Bhunia,
Also mark this issue as completed.
It was great collaborating to your projects.
If there are any more similar issues.
Do assign it to me.
Thanks.
Best Regards 
Kapil
