### ISSUE TITLE
[File Missing]  ".env.example" needed

### ISSUE THREAD

**Issue by MishraTanishq619** [Sayak-Bhunia/mystory#71]
In the project, we are using "MONGO_URL".
But there are no any ".env* " file to get referenced.

Proposed Solution:

- [ ] make a ".env.example" file with needed variables.
- [ ] update ReadMe accordingly.

**Comment by MishraTanishq619** [comment]
I did it myself.

Please label GSSOC 2024 and accept my PR for it.

**Comment by Sayak-Bhunia** [comment]
okay.

**Comment by MishraTanishq619** [comment]
Please add GSSOC Label ...
Thx.

**Comment by Kritika30032002** [comment]
@Sayak-Bhunia add labels to it
