### ISSUE TITLE
 [BUG] : Making the site optimally responsive 

### ISSUE THREAD

**Issue by Vdcds** [Sayak-Bhunia/mystory#83]
Upon conducting a preliminary investigation, I have identified that the website exhibits responsiveness, however, the behavior is inconsistent across various components and pages. This issue can be addressed by implementing responsive design principles, specifically by introducing breakpoints and applying width and height constraints to the affected elements. Within the context of the GSSOC (Girl script Summer of Code) competition, I would be delighted to contribute towards resolving this bug and enhancing the website's responsiveness across diverse devices and screen resolutions.  
@Sayak-Bhunia please look into the concerned matter tell me when to proceed.

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by Kritika30032002** [comment]
@Vdcds any updates?

**Comment by Vaibhavsg17** [comment]
@Sayak-Bhunia & @Kritika30032002  can you assign me this issue
