### ISSUE TITLE
BUG: The signout button should only be visible when a user is logged in

### ISSUE THREAD

**Issue by Sahilll15** [Sayak-Bhunia/mystory#85]
Current Behavior:
The signout button is currently visible to all users, regardless of their authentication status. This can lead to confusion as users who are not logged in see an option that is not applicable to them.

Expected Behavior:
The signout button should only be visible to users who are logged in. When a user is not logged in, this button should be hidden to provide a clearer and more intuitive user experience.

![Screenshot 2024-05-14 at 1 36 26 PM](https://github.com/Sayak-Bhunia/mystory/assets/109215419/a6894e87-cf0b-42a5-ba97-818276e0b4ff)

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by Sayak-Bhunia** [comment]
> Current Behavior:
> The signout button is currently visible to all users, regardless of their authentication status. This can lead to confusion as users who are not logged in see an option that is not applicable to them.
> 
> Expected Behavior:
> The signout button should only be visible to users who are logged in. When a user is not logged in, this button should be hidden to provide a clearer and more intuitive user experience.
> 
> ![Screenshot 2024-05-14 at 1 36 26 PM](https://github.com/Sayak-Bhunia/mystory/assets/109215419/a6894e87-cf0b-42a5-ba97-818276e0b4ff)
> 

Hey I don't want the sign up page to come first I want the landing page to come first what have you done fix it asap.

**Comment by Sayak-Bhunia** [comment]
> Current Behavior:
> The signout button is currently visible to all users, regardless of their authentication status. This can lead to confusion as users who are not logged in see an option that is not applicable to them.
> 
> Expected Behavior:
> The signout button should only be visible to users who are logged in. When a user is not logged in, this button should be hidden to provide a clearer and more intuitive user experience.
> 
> ![Screenshot 2024-05-14 at 1 36 26 PM](https://github.com/Sayak-Bhunia/mystory/assets/109215419/a6894e87-cf0b-42a5-ba97-818276e0b4ff)
> 

There should be a button for sign in and auth not before

**Comment by Sayak-Bhunia** [comment]
take inspo from wrap.dev

**Comment by Sahilll15** [comment]
@psidh worked on it !!

> > Current Behavior:
> > The signout button is currently visible to all users, regardless of their authentication status. This can lead to confusion as users who are not logged in see an option that is not applicable to them.
> > Expected Behavior:
> > The signout button should only be visible to users who are logged in. When a user is not logged in, this button should be hidden to provide a clearer and more intuitive user experience.
> > ![Screenshot 2024-05-14 at 1 36 26 PM](https://private-user-images.githubusercontent.com/109215419/330340582-a6894e87-cf0b-42a5-ba97-818276e0b4ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODIwMjUsIm5iZiI6MTcxNTY4MTcyNSwicGF0aCI6Ii8xMDkyMTU0MTkvMzMwMzQwNTgyLWE2ODk0ZTg3LWNmMGItNDJhNS1iYTk3LTgxODI3NmUwYjRmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxMDE1MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjU5YzY5YjA2OWY1MDVhYTMzNTNmMzNmZjVkMGYyMmFhZDk3OTRmYTM0N2VmZDY4NzhlMDc2Y2NhMjkzNGIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1v0sCf5DDFNxiv1RlmMHvkGmCpUYNVebx7-qnRWfQpo)
> 
> Hey I don't want the sign up page to come first I want the landing page to come first what have you done fix it asap.

@psidh worked on it !!
