### ISSUE TITLE
[feature]: Add User Profile 

### ISSUE THREAD

**Issue by Vaibhavsg17** [Sayak-Bhunia/mystory#88]
Title: [Feature] Create User Profile for Anonymous Confession App

Describe the feature:
The User Profile feature for the Anonymous Confession App will allow users to manage their account settings, preferences, and activity while maintaining anonymity. Each user will have access to a personalized profile where they can configure settings related to their anonymous confessions and interactions.

Key Components of the User Profile:

Basic Information: Users can set a display name (if desired) and upload a profile picture, both of which will be anonymized to maintain privacy. No personally identifiable information (PII) will be required or displayed.

Account Settings: Users will be able to manage their account settings, including changing their password, adjusting notification preferences, and setting privacy controls.

Confession History: This section will allow users to view a history of their submitted confessions, including any responses or interactions from other users, while ensuring all content remains anonymous.

example:
![image](https://github.com/Sayak-Bhunia/mystory/assets/66477893/af2f6791-525b-4c4b-93eb-12d4f0346b33)

**Comment by Vaibhavsg17** [comment]
@Sayak-Bhunia assign me this issue

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by Vaibhavsg17** [comment]
@Sayak-Bhunia update regarding this issue i have completed the UI part.

**Comment by mohdjami** [comment]
@Vaibhavsg17 Are you still working on this one? As a settings page has been created and we need a profile page to view username and other stuff.
