### ISSUE TITLE
Better `Landing Page` with `CTA` button

### ISSUE THREAD

**Issue by psidh** [Sayak-Bhunia/mystory#9]
Presently the `Landing Page` has only a text `mystory` and one scrollable text
I would want to add more context like

- Title of the website
- Tagline
- Intro
- Call-To-Action button

Can I work on this feature?

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by psidh** [comment]
Thank you sir, I will come up the design ASAP

**Comment by psidh** [comment]
**<h1>Current Implementation </h1>**

Following changes 
- `font style` PlusSansJakarta
- One Intro Section with a `device`
- 3 Key Features

    > Experience
    > Privacy 
    > Easy Share
-  Reduced Client Side Rendering
- Added a `Call-To-Action` 
- Button on `Navbar` made custom-styled
- Theme made little more `dark` for more `UI` appeal



https://github.com/Sayak-Bhunia/mystory/assets/116720762/25599d71-8224-453f-a3a2-b51360939246

**Comment by psidh** [comment]
Added a Static NavBar with Glassmorphism property


https://github.com/Sayak-Bhunia/mystory/assets/116720762/997a867f-4bdc-477d-982e-c3af18024cad

**Comment by Sayak-Bhunia** [comment]
can you add gsap or framer motion to the contents  ?

**Comment by Sayak-Bhunia** [comment]
apart from that the concept looks really good.

**Comment by psidh** [comment]
I tried framer motion, but it was clogging the website performace so i avoided it, shall I add AOS (animation on scroll) to the contents? I have tried it , if you want I can add that.

**Comment by Sayak-Bhunia** [comment]
yeah add that.
i have also faced the same problem while working with framer motion though it provides lot of flexibility but has some cons also.

**Comment by Sayak-Bhunia** [comment]
can you tell where did you get this type of design border like cross on the corners i have also seen that many times but never found the resource here's an example sonicrypt.vercel.app

**Comment by psidh** [comment]
Here you find them: https://ui.aceternity.com/components
Configuration is also provided in docs

I have added the aos also , this is the preview

https://github.com/Sayak-Bhunia/mystory/assets/116720762/d77507c4-da78-439c-8f63-2024d4a4d6c6

**Comment by psidh** [comment]
Shall I make a PR?

**Comment by Sayak-Bhunia** [comment]
> Shall I make a PR?

Yes looks freaking good 👍🏻

**Comment by psidh** [comment]
Okay :)

**Comment by Sayak-Bhunia** [comment]
> Okay :)

Hey the branch you created has conflicts with the main branch other than ur work like there was a adding of time string so GitHub saying that clean merge cannot be done so I am suggesting you to update the ur branch according to the main branch.

**Comment by psidh** [comment]
Okay I would update the branch once,

**Comment by Sayak-Bhunia** [comment]
merged! great work man great work.
i truly admire your work.
