### ISSUE TITLE
Nav bar is still not responsive for mobiles.

### ISSUE THREAD

**Issue by MishraTanishq619** [Sayak-Bhunia/mystory#93]
I think last 3 or 4 buttons are under one div only.
Thus they are not responsive.

Purposed solution:

- [ ] Do all buttons in different divs respectively.

**Comment by MishraTanishq619** [comment]
I would Like to work on this myself.
Please assign me this, for GSSOC.

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by SnehansuBehera** [comment]
@Sayak-Bhunia I want to contribute to this issue and make the navbar responsive for every screen sizes. So I request you to please assign me the issue under GSSoC'24. I will fix it asap.

![Screenshot 2024-05-15 215148](https://github.com/Sayak-Bhunia/mystory/assets/121883802/34bb50a0-eed7-403c-8001-a8313f2545c6)

**Comment by Sayak-Bhunia** [comment]
> @Sayak-Bhunia I want to contribute to this issue and make the navbar responsive for every screen sizes. So I request you to please assign me the issue under GSSoC'24. I will fix it asap.
> 
> ![Screenshot 2024-05-15 215148](https://github.com/Sayak-Bhunia/mystory/assets/121883802/34bb50a0-eed7-403c-8001-a8313f2545c6)
> 

assigned.

**Comment by SnehansuBehera** [comment]
@Sayak-Bhunia it's already assigned to someone else or you are assigning me to do the job??

**Comment by Sayak-Bhunia** [comment]
> @Sayak-Bhunia it's already assigned to someone else or you are assigning me to do the job??

You were making the navbar responsive not fixing it currently it's not even working so I assigned it to @Vaibhavsg17

**Comment by Sayak-Bhunia** [comment]
You can still work on this issue if u want.

**Comment by Vaibhavsg17** [comment]
> > @Sayak-Bhunia it's already assigned to someone else or you are assigning me to do the job??
> 
> You were making the navbar responsive not fixing it currently it's not even working so I assigned it to @Vaibhavsg17

Okay, I will work on it
