### ISSUE TITLE
Navbar buttons are still difficult to access.

### ISSUE THREAD

**Issue by MishraTanishq619** [Sayak-Bhunia/mystory#94]
They are still harder to access.
On hovering them, change of their size of whole button, thus whole navbar makes it difficult to access buttons.

Purposed solution:
- [ ]  buttons should have a "Wrapper div".

After wrapping, buttons will show animations but will not affect the overall sizes.
Therefore, it will be easier for one to access them.

**Comment by MishraTanishq619** [comment]
I would Like to work on this myself.
Please assign me this, for GSSOC.

**Comment by Sayak-Bhunia** [comment]
assigned.

**Comment by MishraTanishq619** [comment]
suggest some changes...

[Screencast from 16-05-24 10:06:16 AM IST.webm](https://github.com/Sayak-Bhunia/mystory/assets/127047332/fa95d8eb-c21f-4ba6-8e08-2383fa7b0af6)
