### ISSUE TITLE
[BUG] Unable to Create Confessions.

### ISSUE THREAD

**Issue by mohdjami** [Sayak-Bhunia/mystory#95]
[Bug] Due to wrong user id in the backend route.js folder of confessions files users will not be able to create new confessions.

Proposed changes:
Create a proper helper function and from inbuilt getServerSession() from next-auth fetch the current user and return the useId.
This will solve the issue.

Video: 

https://github.com/Sayak-Bhunia/mystory/assets/114595881/f67f7072-9d8b-484e-b05c-8fcae65bec7c

**Comment by Sayak-Bhunia** [comment]
> [Bug] Due to wrong user id in the backend route.js folder of confessions files users will not be able to create new confessions.
> 
> Proposed changes:
> Create a proper helper function and from inbuilt getServerSession() from next-auth fetch the current user and return the useId.
> This will solve the issue.
> 
> Video: 
> 
> https://github.com/Sayak-Bhunia/mystory/assets/114595881/f67f7072-9d8b-484e-b05c-8fcae65bec7c
> 
> 

Fix this.

**Comment by mohdjami** [comment]
> > [Bug] Due to wrong user id in the backend route.js folder of confessions files users will not be able to create new confessions.
> > Proposed changes:
> > Create a proper helper function and from inbuilt getServerSession() from next-auth fetch the current user and return the useId.
> > This will solve the issue.
> > Video:
> > 
> >   
> >     
> >     
> > 
> >     confess.mp4
> 
> Fix this.

#96 I already fixed this issue in this PR. You can close this issue now.
