### ISSUE TITLE
[BUG]: The navbar is not working 

### ISSUE THREAD

**Issue by Sayak-Bhunia** [Sayak-Bhunia/mystory#99]
Please fix it asap.

**Comment by Vaibhavsg17** [comment]
@Sayak-Bhunia i will fix , assign me

**Comment by Sayak-Bhunia** [comment]
> @Sayak-Bhunia i will fix , assign me 

assigned.

**Comment by MishraTanishq619** [comment]
Fixing with #94 

[Screencast from 16-05-24 10:36:53 AM IST.webm](https://github.com/Sayak-Bhunia/mystory/assets/127047332/046e01e6-ca31-4928-8165-841ec6aa5966)

**Comment by Vaibhavsg17** [comment]
i have already fixed it

**Comment by Vaibhavsg17** [comment]
create a pull request for the same
